from .base import StyleConfig, BackgroundConfig

STYLES: dict[str, StyleConfig] = {
    # ─── CANVAS STYLES ────────────────────────────────────────────────────────
    "whiteboard": StyleConfig(
        name="Whiteboard",
        category="canvas",
        background=BackgroundConfig(color="#FFFFFF", texture="none"),
        palette=["#1A1A1A", "#E63946", "#457B9D", "#2A9D8F"],
        title_font_size=52,
        body_font_size=32,
        text_color="#1A1A1A",
        accent_color="#E63946",
        drawing_effect="pen",
        reveal_speed=0.5,
        transition="wipe_left",
        image_prompt_suffix="rich hand-drawn whiteboard illustration with expressive characters, black marker outlines, red emphasis marks, blue technical details, clean white background",
        font_style="sans",
    ),
    "chalkboard_color": StyleConfig(
        name="Chalkboard Color",
        category="canvas",
        background=BackgroundConfig(color="#1B3A2D", texture="chalk"),
        palette=["#FFFFFF", "#F7C948", "#7EC8E3", "#F4A261"],
        title_font_size=50,
        body_font_size=30,
        text_color="#FFFFFF",
        accent_color="#F7C948",
        drawing_effect="chalk",
        reveal_speed=0.45,
        transition="fade",
        image_prompt_suffix="layered colorful chalk drawing on dark green chalkboard, visible chalk dust texture, expressive teacher-style doodles, warm yellow highlights and blue technical notes",
        font_style="chalk",
    ),
    "chalkboard_white": StyleConfig(
        name="Chalkboard White",
        category="canvas",
        background=BackgroundConfig(color="#111111", texture="chalk"),
        palette=["#EEEEEE", "#CCCCCC", "#AAAAAA"],
        title_font_size=50,
        body_font_size=30,
        text_color="#EEEEEE",
        accent_color="#FFFFFF",
        drawing_effect="chalk",
        reveal_speed=0.45,
        transition="fade",
        image_prompt_suffix="detailed white chalk drawing on black chalkboard, chalk dust texture, expressive simple characters, arrows, boxed callouts, classroom explainer composition",
        font_style="chalk",
    ),
    "modern_minimal": StyleConfig(
        name="Modern Minimal",
        category="canvas",
        background=BackgroundConfig(color="#F8F9FA", texture="none"),
        palette=["#212529", "#4361EE", "#7209B7", "#3A0CA3"],
        title_font_size=54,
        body_font_size=32,
        text_color="#212529",
        accent_color="#4361EE",
        drawing_effect="pen",
        reveal_speed=0.55,
        transition="fade",
        image_prompt_suffix="modern clean explainer illustration, precise black linework, restrained blue and violet accents, expressive tech characters, organized UI-like flow without clutter",
        font_style="sans",
    ),
    "sharpie": StyleConfig(
        name="Sharpie Style",
        category="canvas",
        background=BackgroundConfig(color="#0D0D0D", texture="none"),
        palette=["#FFFFFF", "#FF6B35", "#FFD166", "#06D6A0"],
        title_font_size=56,
        body_font_size=34,
        text_color="#FFFFFF",
        accent_color="#FF6B35",
        drawing_effect="marker",
        reveal_speed=0.6,
        transition="wipe_left",
        image_prompt_suffix="bold sharpie marker illustration on a dark board, thick white and orange outlines, graphic novel contrast, expressive faces, confident hand-lettered callouts",
        font_style="marker",
    ),
    "playful": StyleConfig(
        name="Playful",
        category="canvas",
        background=BackgroundConfig(color="#FFF9C4", texture="paper"),
        palette=["#FF595E", "#FFCA3A", "#6A4C93", "#1982C4", "#8AC926"],
        title_font_size=54,
        body_font_size=32,
        text_color="#2D2D2D",
        accent_color="#FF595E",
        drawing_effect="marker",
        reveal_speed=0.5,
        transition="fade",
        image_prompt_suffix="fun colorful cartoon explainer, rounded expressive characters, playful props, bright accent colors, thick black outlines, energetic arrows and speech bubbles",
        font_style="marker",
    ),
    "editorial": StyleConfig(
        name="Editorial",
        category="canvas",
        background=BackgroundConfig(color="#F5F0E8", texture="paper"),
        palette=["#2C2C2C", "#C0392B", "#2C3E50"],
        title_font_size=52,
        body_font_size=30,
        text_color="#2C2C2C",
        accent_color="#C0392B",
        drawing_effect="pen",
        reveal_speed=0.4,
        transition="fade",
        image_prompt_suffix="editorial ink illustration with cross-hatching, expressive people and objects, selective red emphasis, newspaper explainer style, sophisticated but readable composition",
        font_style="sans",
    ),
    "technical": StyleConfig(
        name="Technical",
        category="canvas",
        background=BackgroundConfig(color="#0A1628", texture="dark_paper"),
        palette=["#00B4D8", "#90E0EF", "#CAF0F8", "#ADE8F4"],
        title_font_size=48,
        body_font_size=28,
        text_color="#CAF0F8",
        accent_color="#00B4D8",
        drawing_effect="pen",
        reveal_speed=0.4,
        transition="fade",
        image_prompt_suffix="technical blueprint explainer on dark background, glowing cyan linework, precise system arrows, labeled devices, small expressive robot or computer character, schematic clarity",
        font_style="mono",
    ),
    "illustration": StyleConfig(
        name="Illustration",
        category="canvas",
        background=BackgroundConfig(color="#FAFAFA", texture="none"),
        palette=["#2D3047", "#E84855", "#F18F01", "#3BB273"],
        title_font_size=52,
        body_font_size=30,
        text_color="#2D3047",
        accent_color="#E84855",
        drawing_effect="none",
        reveal_speed=0.35,
        transition="fade",
        image_prompt_suffix="detailed colorful editorial illustration, expressive human characters, clear metaphorical objects, strategic red and green accents, polished hand-drawn linework",
        font_style="sans",
    ),

    # ─── SKETCH STYLES ────────────────────────────────────────────────────────
    "classic_bw": StyleConfig(
        name="Classic Style B&W",
        category="sketch",
        background=BackgroundConfig(color="#0A0A0A", texture="dark_paper"),
        palette=["#EEEEEE", "#CCCCCC", "#999999"],
        title_font_size=48,
        body_font_size=28,
        text_color="#EEEEEE",
        accent_color="#FFFFFF",
        drawing_effect="pen",
        reveal_speed=0.35,
        transition="fade",
        image_prompt_suffix="classic black and white pen-and-ink explainer, detailed cross-hatching, expressive characters, arrows and caption boxes, engraved newspaper illustration feel",
        font_style="sans",
    ),
    "classic_color": StyleConfig(
        name="Classic Style Color",
        category="sketch",
        background=BackgroundConfig(color="#F8F4EF", texture="paper"),
        palette=["#1A1A2E", "#E94560", "#F5A623", "#16213E"],
        title_font_size=50,
        body_font_size=30,
        text_color="#1A1A2E",
        accent_color="#E94560",
        drawing_effect="pen",
        reveal_speed=0.4,
        transition="fade",
        image_prompt_suffix="colorful classic editorial comic illustration, detailed character art, expressive faces, hand-drawn arrows, selective red and gold emphasis, rich scene detail",
        font_style="sans",
    ),
    "professional_clean": StyleConfig(
        name="Professional Clean",
        category="sketch",
        background=BackgroundConfig(color="#FFFFFF", texture="none"),
        palette=["#2B2D42", "#8D99AE", "#EF233C", "#6C63FF"],
        title_font_size=52,
        body_font_size=30,
        text_color="#2B2D42",
        accent_color="#6C63FF",
        drawing_effect="none",
        reveal_speed=0.5,
        transition="fade",
        image_prompt_suffix="professional clean business explainer, expressive office characters, crisp flow arrows, flat icons with black outlines, structured layout, blue and red emphasis",
        font_style="sans",
    ),
    "infographics": StyleConfig(
        name="Infographics",
        category="sketch",
        background=BackgroundConfig(color="#F0F4F8", texture="none"),
        palette=["#2C3E50", "#3498DB", "#E74C3C", "#27AE60", "#F39C12"],
        title_font_size=50,
        body_font_size=28,
        text_color="#2C3E50",
        accent_color="#3498DB",
        drawing_effect="none",
        reveal_speed=0.5,
        transition="wipe_left",
        image_prompt_suffix="infographic explainer illustration, clean boxes and arrows, small expressive characters, colorful structured layout, charts and callouts that support the story",
        font_style="sans",
    ),
    "dry_erase": StyleConfig(
        name="Dry Erase",
        category="sketch",
        background=BackgroundConfig(color="#F2EFE4", texture="paper"),
        palette=["#1B1B1B", "#2563EB", "#DC2626", "#16A34A"],
        title_font_size=52,
        body_font_size=32,
        text_color="#1B1B1B",
        accent_color="#2563EB",
        drawing_effect="marker",
        reveal_speed=0.55,
        transition="wipe_left",
        image_prompt_suffix="dry erase marker drawing on whiteboard, colorful marker strokes, expressive teaching characters, bold black outlines, red and blue annotations, natural board composition",
        font_style="marker",
    ),
    "creative_color": StyleConfig(
        name="Creative Color",
        category="sketch",
        background=BackgroundConfig(color="#FFFEF0", texture="paper"),
        palette=["#FF006E", "#FB5607", "#FFBE0B", "#3A86FF", "#8338EC"],
        title_font_size=54,
        body_font_size=32,
        text_color="#1A1A1A",
        accent_color="#FF006E",
        drawing_effect="marker",
        reveal_speed=0.5,
        transition="fade",
        image_prompt_suffix="creative hand-drawn doodle explainer, expressive linework, mixed visual metaphors, colorful sketchbook accents, characters, arrows, speech bubbles and useful callouts",
        font_style="marker",
    ),
    "crayon_color": StyleConfig(
        name="Crayon Color",
        category="sketch",
        background=BackgroundConfig(color="#FFF8E7", texture="paper"),
        palette=["#E63946", "#F4A261", "#2A9D8F", "#264653", "#E9C46A"],
        title_font_size=52,
        body_font_size=30,
        text_color="#2D2D2D",
        accent_color="#E63946",
        drawing_effect="crayon",
        reveal_speed=0.45,
        transition="fade",
        image_prompt_suffix="colorful crayon explainer illustration, textured crayon marks, warm storybook characters, simple expressive faces, chunky arrows and friendly visual metaphors",
        font_style="sans",
    ),
    "improved_beta": StyleConfig(
        name="Improved Beta",
        category="sketch",
        background=BackgroundConfig(color="#F8FAFC", texture="none"),
        palette=["#1E293B", "#3B82F6", "#10B981", "#8B5CF6"],
        title_font_size=52,
        body_font_size=30,
        text_color="#1E293B",
        accent_color="#3B82F6",
        drawing_effect="none",
        reveal_speed=0.55,
        transition="fade",
        image_prompt_suffix="modern tech explainer illustration, expressive laptop or computer character, clean digital line art, software icons, flow arrows, blue and green accents, contemporary UI clarity",
        font_style="sans",
    ),
}


def get_style(name: str) -> StyleConfig:
    key = name.lower().replace(" ", "_").replace("-", "_")
    if key not in STYLES:
        available = ", ".join(STYLES.keys())
        raise ValueError(f"Unknown style '{name}'. Available: {available}")
    return STYLES[key]


def list_styles() -> list[tuple[str, str, str]]:
    return [(key, s.name, s.category) for key, s in STYLES.items()]
